import type { Metadata } from 'next';
import { GeistMono } from 'geist/font/mono';
import './globals.css';
import Navbar from '@/pages/components/Navbar';

// const inter = GeistMono({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'SgUniAnalysis',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body>
                <Navbar />
                {children}
            </body>
        </html>
    );
}
